### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rsrinath14** [okutewonah/okutewonah#2]
->You could maybe add links to your social media (example: Twitter, LinkedIn, Your portfolio website etc) so that people could 
     contact you.
->If you would like to display your GitHub stats, check this out https://github.com/anuraghazra.

**Comment by rsrinath14** [comment]
Displaying the icons of the technologies that you are familiar with would look good too.

**Comment by okutewonah** [comment]
I should really do that. I will get the idea from what you have done with yours

**Comment by okutewonah** [comment]
thanks for the idea <3
